# Noncompliant [[sc=1;ec=8]] {{Add a description to this feature.}}
Feature: My feature Missing feature description

  Scenario: Scenario 1 Missing feature description
    Given blabla given...
    When blabla when...
    Then blabla then...
