Feature: Feature duplicated scenario names
  Blabla...

  Background: background name blabla
    Given blabla given b1...

  Scenario: scenario name blabla
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario name blabla
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario:
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: scenario outline name blabla
    Given blabla given...<number>
    When blabla when...
    Then blabla then...

    Examples: examples name blabla
      | number |
      | 1      |
      | 2      |
