@tag
@abc
Feature: My feature indentation custom ok
    blabla...
    blabla...

    Background: blabla background indentation custom ok
        blabla...
        blabla...
        Given blabla given1...

    @def
    Scenario: Scenario 1 indentation custom ok
        blabla...
        blabla...
        Given blabla given...
        When blabla when...
        Then blabla then...

    @ghi @jkl
    Scenario Outline: Scenario 2 indentation custom ok
        blabla...
        blabla...
        Given blabla given...
        When blabla when...
            | data |
            | 2    |
        Then blabla then...<data>
            """string
            blabla...
              blabla...
            """

        @mno
        @pqr @stu
        Examples: blabla examples indentation custom ok
            blabla...
            blabla...
            | data |
            | 1    |
            | 2    |
