@tag
@tag1
Feature: My feature indentation default OK
  Blabla...
  Blabla...

  Background: Blabla background indentation default OK
    Blabla...
    Blabla...
    Given Blabla given blabla...

  @abc @def
  Scenario: Scenario 1 indentation default OK
    Blabla...
    Blabla...
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  @ghi
  Scenario Outline: Scenario 2 indentation default OK
    Blabla...
    Blabla...
    Given Blabla given...
    When Blabla when...<data>
      | data |
      | 2    |
    Then Blabla then...
      """string
      Blabla...
        Blabla...
      """

    @jkl
    @lmn @opq
    Examples: Blabla examples indentation default OK
      Blabla...
      Blabla...
      | data |
      | 1    |
      | 2    |
