@bar
Feature: My feature...

  @foo
  Scenario: Scenario 1
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  @mytag
  Scenario: Scenario 2
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
