# Noncompliant [[sc=10;ec=27]] {{Remove this usage of "WTF".}}
Feature: WTF My feature...

  Scenario: Scenario #1
    Given blabla...
    When blabla...
    Then blabla...

  # Noncompliant [[sc=13;ec=28]] {{Remove this usage of "WTF".}}
  Scenario: Scenario WTF #2
    Given blabla...
    When blabla...
    Then blabla...
