@bar
Feature: My feature...

  @foo
  Scenario: Scenario 1
    Given blabla given...
    When blabla when...
    Then blabla then...

  @mytag
  Scenario: Scenario 2
    Given blabla given...
    When blabla when...
    Then blabla then...
