# Noncompliant [[sc=1;ec=8]] {{The number of scenarios (13) is greater that the maximum allowed (12). Split the scenarios into different features.}}
Feature: My feature max number scenarios greater than default threshold...
  Blabla...

  Background:
    Given blabla...

  Scenario: scenario #1 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: scenario #2 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...<data>
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #4 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #5 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #6 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #7 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #8 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #9 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #10 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #11 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #12 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #13 max number scenarios greater than default threshold
    Given blabla...
    When blabla...
    Then blabla...
