Feature: My feature max number scenarios lower than default threshold...
  Blabla...

  Background:
    Given blabla given1...

  Scenario: scenario #1 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: scenario #2 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...<data>
    Then blabla then...
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #4 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #5 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #6 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #7 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #8 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #9 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #10 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #11 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #12 max number scenarios lower than default threshold
    Given blabla given...
    When blabla when...
    Then blabla then...
