Feature: My feature max number steps background...
  Blabla...

  Background:
    Given Blabla given1...
    And Blabla b1...
    And Blabla b2...
    And Blabla b3...
    And Blabla b4...

  Scenario: Scenario #1 max number steps background
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
    And Blabla t1...
    And Blabla t2...
    And Blabla t3...
    And Blabla t4...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (13, greater than 12 allowed).}}
  Scenario: Scenario #2 max number steps background
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
    And Blabla t1...
    And Blabla t2...
    And Blabla t3...
    And Blabla t4...
    And Blabla t5...
