Feature: My feature max number steps background...

  Background:
    Given blabla...
    And blabla...
    And blabla...
    And blabla...
    And blabla...

  Scenario: scenario #1 max number steps background
    Given blabla...
    When blabla...
    Then blabla...
    And blabla...
    And blabla...
    And blabla...
    And blabla...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (13, greater than 12 allowed).}}
  Scenario: scenario #2 max number steps background
    Given blabla...
    When blabla...
    Then blabla...
    And blabla...
    And blabla...
    And blabla...
    And blabla...
    And blabla...
