# language: fr
@mytag
Fonctionnalité: My feature...
  blaba...
  blabla...

  # blabla...
  #blabla...

  Contexte: :
    Etant donné Blabla given...

  Scénario: : Scenario 1
    Soit Blabla given...
    Lorsque Blabla when...
    Alors Blabla then...

  @tag
  Plan du Scénario: Outline: Scenario 2
    Soit Blabla given...
    Lorsque Blabla when...
    Alors Blabla then...

    Exemples: :
      | var |
      | 1   |
      | 2   |

  Scénario: : Scenario 3
    Soit Blabla given...
    Lorsque Blabla when...
    Alors Blabla then...
