Feature: My feature...
  blaba...
  blabla...

  # blabla...
  #blabla...

  Background:
    Given Blabla given...

  Scenario: Scenario 1
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Background:
    Given Blabla given...

  @tag
  Scenario Outline: Scenario 2
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

    Examples:
      | var |
      | 1   |
      | 2   |

  Scenario: Scenario 3
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
