Feature: My feature...
  blaba...
  blabla...

  # blabla...
  #blabla...

  Background:
    Given blabla given...

  Scenario: Scenario 1
    Given blabla given...
    When blabla when...
    Then blabla then...

  Background:
    Given blabla given...

  @tag
  Scenario Outline: Scenario 2
    Given blabla given...
    When blabla when...
    Then blabla then...

    Examples:
      | var |
      | 1   |
      | 2   |

  Scenario: Scenario 3
    Given blabla given...
    When blabla when...
    Then blabla then...
