Feature: My feature utf8...

  Scenario: Scenario 1 utf8
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 utf8
    Given blabla...
    When blabla...
    Then blabla...
