# Noncompliant [[sl=0]] {{Remove the Byte Order Mark (BOM).}}
Feature: My feature...

  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
