Feature: My feature utf8...
  Blabla...

  Scenario: Scenario 1 utf8
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 utf8
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
