Feature: My feature file name...

  Scenario: Scenario 1 file name
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 file name
    Given blabla...
    When blabla...
    Then blabla...
