Feature: My feature file name OK...
  Blabla...

  Scenario: Scenario 1 - file name OK
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 - file name OK
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
