Feature: My feature file name ok...
  Blabla...

  Scenario: Scenario 1 file name ok
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 file name ok
    Given blabla given...
    When blabla when...
    Then blabla then...
