Feature: My feature file name ko custom...

  Scenario: Scenario 1 file name ko custom
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 file name ko custom
    Given blabla...
    When blabla...
    Then blabla...
