Feature: My feature file name ok...

  Scenario: Scenario 1 file name ok
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 file name ok
    Given blabla...
    When blabla...
    Then blabla...
