Feature: My feature file name ko custom...
  Blabla...

  Scenario: Scenario 1 file name ko custom
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 file name ko custom
    Given blabla given...
    When blabla when...
    Then blabla then...
