Feature: My feature file name KO custom...
  Blabla...

  Scenario: Scenario 1 file name KO custom
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 file name KO custom
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
