dist: trusty
sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "d16AORNkx1eqauQEjOwm9t0YePkTWNs5Pd9ubYRLa487KLNj7szmGWWTla8SpLQo9a2U9NUFtF9JeMP4qcBuJNN6FYdJ+Hm/2RpgROSO7f/Cdu2DGWtj9eku6cJKT6V3R9fLCj01WKrh8q9k/GbHrcDNaWFiOdD7l25j8mT3QCvFVY0Qpquk9CzOCaTmS9+cnw4OSOlFJ5bsyRba4c4UC3TD3aq4kzmwORJpeCxmX3q/02EbUPCkJhtmnUecmuCq1vJehn+oPoGRzt0aLsDdnIbdauq732xneZN+Ey7LyMP3KIcu053YGhisznyzNX+ti366WRtUGV38T5jLK8SLgHjjGjwur3V7qFArOEWF41M+ZNuQrbh82XtYIilypdq34qoPj1UGCkJlNz5knqP86q1/OadP5AAlWSvTeyMEdxTYzGBebVEHiuXQyE5xHwmXvA/+mGhYpnzlXhRVELZsapJaDAUVtjAXBs71SgholQpNPXi1WRug3YQoDytl9vSDmxiy2qPcw+sEqrCKKU2nZKefuRPY64XyaZJaTBebFG0OyBFQuMZ/3+bt1XilaPZ6svihG3AB18y4QN9N5HW7bZWRqPHJQBjXoJT2kXHokh/FdbfuL9clXxYkQSfyiuWCrUZiKRa2tg5xlxwGM8MFumQ0Rc0cUYMKWrIIWgE6NzI="
    - secure: "X0UyV52UIdhgYWgHPIQeJFuAsJoSw7hb6thccws9DC+AKbKRWQTA0TDw9zHhc2UbdEaplXx+Rz5hrL1f19hv5pc2WDLpkQRAqE1Xtdw6sLLzuVea3pCHvONgVkqJ1JXurkPcBqwtamWur+x7i3/LC7gA8k+cQogY8i4VP8z1kOE44ZZEbtA4lXPhApFnf5sOszR0XKQ7EF01vuNYFtZnUpmkzPH5l71ommAA5ugeo1YfODVusnEpocGby0bEFK0rycizxSajzf3+cZUvXtJtvxcLMYZR7eks2KvtPvTOO2e3vXLc7UHZpYoD7fNdv46ID5E5lTlFuKkHID7txVNnC2AfDOPWRT/mEJ9lMD2p031PsvnAkBMALJloyAABwRxPgdDAoA84OeawLtFfDTvQWCR3WmmxixnHmFlxnQMk5g5APjNGr14gP0HhwuUtOkGJWRjR+dkFuSM9TLmjJ49C9v4/X8o3eRhbBkHyxIbg7EjmLHBUsTz60311/XQgIDtbxbsvNvCGOI2lT66rtDuewv9rBjet0OkghX0T00fns3LnsxKwP1ERAgJo994sNDqIgDsKP9fDV0LwRGFWeE0JtpoBqYio5mLozB8yZe95ZE6ZlXwfjKKk+p84TbDelZPF6yABZkvxBOnVKp+Cmf6Xc56Ku0R0UamemUahI68jsMw="

  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: ./travis.sh
