language: java

jdk:
  - oraclejdk8

addons:
  sonarqube: true

env:
  global:
    - secure: "q/Kae98eJOWXmUvd1dD2fnTzzFUrc0u9G1gtaf0p+KEjRTL6hDrHxKTnhzC1G6OvN4GtBh9/wAOiEWoSTYV+SXOQXTDYnm584ZvG5qZ7cXj+sWU9wceEeNkqfiSRXaoUIeYFTltgKVNdCFk0pCczSxY8IijE2nT80BpzcM1PoCRfVBKg9BJQkgnOHTXgdshILp2aiBIcGtY1g6+4BPoPwIwkvm7K2HtsmwX1hmkaVSAp42rSrIfNg8EWPcF22rt89TbOvrC4loH/JpxFjhSM8j4J4T68a4JD/FjXaoglE/Cg1bQCGZ3rEvzXBUzb/EAfpm44wZEkPjht8AvFAaCtX2kE9uzbjrJS0AK2zpoh2mSmPWl3JQncdWEyiLmTL6YfKJNJf3y/0njDeZKZ1mJ52/obC9FYHQX1jiycEFIt5MgqdFlNqJDRAVfUtZlhjS9umx6a5A8hwGztcNpttFChTd3DShZgBERfduwr/0VSpCctsIKJOTqeBBHd3+zC90fPZiS6hswumaTGMmbRnCzRCocJJ5k0mDctIvdcmSh9i8Y/5Ny+fusiQGlXejxL4T4zo6CwWkBnA/0s6nPsieMaJbhB6E9Mvz4sE6MtfnFseTlGSoJVXqX0fx3koQUVti3freNOSGnsa3VZWEeb7KzpEizjFCBwyvQ9Lfh6pJv16Ks="
    - secure: "GX2HWVU69u6V2Di05rPI1RCVozismdTiCXrl3b5HkHwk939k2HgNh2S0nKN2dxmLQCzZ7lUM7iRGVUH93Q0W+yYn94MAE8qtTXaqySwdyaOrqfidte2ZFMp1bRja9fW2eRYjKpn687xCtZ92wc7s+BbXFQPOmo+0B0x1F2aq/CuM+iUWm+7MdcTudXB2UKSN3bSiVWIaQ1m4vbrd7h3Icxc5yo+5G2mc04gS8x2qmVlw29d7nVkBIpHwf3n5odyJY/mRXfN33AZ5U9EastJ5l9neoS3VgnxwtTL5Nfo8e4d+oSTOX3RXErQYyWvNGz/LtRRbgFiCAaFHknu8apFUi/kW+tTUL8fkhPNRIGwVBLkpFnQabvPl8LgOzWoS18Rf5CA8p2lXU1JyPqL8RmzBiA6eBotMDC+o+9XbtZq6DHJx0Ip1Juer/SRXag/YiSRRs89PxDoGOxzeuNHXNQKyhPUjFaO502K8SP2BoJhxQrfkEoqrZXWThNp53Qs7xPJy0+qUNJgpjXqYDMiMf1B0HERW83S28M5ZkgcIajUFq4NXTY1wqLv08CGAJcCRICh5e3FjhO7VsOjkSeLQfc1kKOlEhKwOkV+97BRyHXxmig1mmMBUu95sHOVvQkqvt6+PErddYxFzDyUnhKyWEzwOsgU8HOWIb63ZM8edR8zgWJs="
  matrix:
    - SQ_VERSION=LTS
    - SQ_VERSION=LATEST_RELEASE
    - SQ_VERSION=DEV

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script: ./travis.sh
