version: "{build}"

cache:
  - C:\Users\appveyor\.m2

install:
  - SET JAVA_HOME=C:\Program Files\Java\jdk1.8.0
  - SET PATH=C:\maven\apache-maven-3.3.9\bin;%JAVA_HOME%\bin;%PATH%

  - appveyor DownloadFile http://www.us.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
  - 7z x apache-maven-3.3.9-bin.zip -oC:\maven

environment:
  matrix:
    - SQ_VERSION: "LTS"
    - SQ_VERSION: "LATEST_RELEASE"
    - SQ_VERSION: "DEV"

platform:
  - x86
  - x64

build_script:
  - mvn clean install -B -DskipTests=true -Dmaven.javadoc.skip=true

test_script:
  - mvn clean install -B -Djna.nosys=true
  - cd its
  - mvn clean install -B -Djna.nosys=true -Dsonar.runtimeVersion=%SQ_VERSION%

