Feature: My feature...

  # blabla...
  # blabla...
  Scenario: Scenario #1
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: Scenario #3
    Given blabla given...
    When blabla when...
    Then blabla then...

  Examples:
  |d1|
