Feature: My feature...

  # blabla...
  # blabla...
  Scenario: Scenario #1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: Scenario #3
    Given blabla...
    When blabla...
    Then blabla...

  Examples:
  |d1|
