Feature: My feature New line end of file
  Blabla...

  Scenario: Scenario #1 New line end of file
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #2 New line end of file
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
