Feature: My feature New line end of file
  Blabla...

  Scenario: Scenario #1 New line end of file
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario #2 New line end of file
    Given blabla given...
    When blabla when...
    Then blabla then...
