Feature: My feature No new line end of file
  Blabla...

  Scenario: Scenario #1 No new line end of file
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 No new line end of file
    Given blabla given...
    When blabla when...
    Then blabla then...