Feature: My feature No new line end of file
  Blabla...

  Scenario: Scenario #1 No new line end of file
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 No new line end of file
    Given Blabla given...
    When Blabla when...
    Then Blabla then...