# Noncompliant [[sc=1;ec=8]] {{Add a name to this feature.}}
Feature:
  Blabla...

  Scenario: Scenario #1 Missing feature name
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
