Feature: My feature Not only given
  Blabla...

  Background:
    Given blabla g1...
    And blabla g2...
    # Noncompliant [[sc=5;ec=24]] {{Move this non-Given step out of Background.}}
    When blabla when...
    # Noncompliant [[sc=5;ec=21]] {{Move this non-Given step out of Background.}}
    And blabla w1...
    Given blabla g3...

  Scenario: Scenario 1 Not only given
    Given blabla given1...
    When blabla when1...
    Then blabla then1...
