Feature: My feature Not only given
  Blabla...

  Background:
    Given blabla...
    And blabla...
    # Noncompliant [[sc=5;ec=19]] {{Move this non-Given step out of Background.}}
    When blabla...
    # Noncompliant [[sc=5;ec=18]] {{Move this non-Given step out of Background.}}
    And blabla...
    Given blabla...

  Scenario: Scenario 1 Not only given
    Given blabla...
    When blabla...
    Then blabla...
