Feature: My feature Only given
  Blabla...

  Background:
    Given Blabla g0...
    And Blabla g1...
    But Blabla g2...
    Given Blabla g3...

  Scenario: Scenario 1 Only given
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
