Feature: My feature Only given

  Background:
    Given blabla...
    And blabla...
    But blabla...
    Given blabla...

  Scenario: Scenario 1 Only given
    Given blabla...
    When blabla...
    Then blabla...
