Feature: My feature Comment regular expression
  Blabla...

  # WTF!
  # wtf: abc
  # Hello
  Scenario: Scenario 1 Comment regular expression
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 Comment regular expression
    Given blabla given...
    When blabla when...
    Then blabla then...
