Feature: My feature Comment convention
  Blabla...

#My comments
# My comments
  Scenario: Scenario 1 Comment convention
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 Comment convention
    Given blabla...
    When blabla...
    Then blabla...
