Feature: My feature Comment regular expression
  Blabla...

  # WTF!
  # wtf: abc
  # wtf: wtf
  # Hello
  Scenario: Scenario 1 Comment regular expression
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 Comment regular expression
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
