Feature: My feature Comment convention
  Blabla...

#My comments
# My comments
  Scenario: Scenario 1 Comment convention
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 Comment convention
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
