Feature: My feature Comment regular expression
  Blabla...

  # WTF!
  # wtf: abc
  # Hello
  Scenario: Scenario 1 Comment regular expression
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 Comment regular expression
    Given blabla...
    When blabla...
    Then blabla...
