Feature: My feature End line characters
  Blabla...

  Scenario: Scenario 1 End line characters
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 End line characters
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
