Feature: My feature End line characters

  Scenario: Scenario 1 End line characters
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 End line characters
    Given blabla...
    When blabla...
    Then blabla...
