Feature: My feature...

  # Noncompliant {{Take the required action to fix the issue indicated by this comment.}}
  # FIXME: blabla

  # Noncompliant {{Take the required action to fix the issue indicated by this comment.}}
  #FIXME: blabla

  # Noncompliant {{Take the required action to fix the issue indicated by this comment.}}
  #[[FIXME]] blabla

  # fixmeforthefirsttime

  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
