# language: fr
Fonctionnalité: My feature french
  Blabla...

  Scénario: My scenario 1 french
    # Noncompliant [[sc=5;ec=7]] {{Replace this star prefix with one of the Given/When/Then prefixes.}}
    * Blabla...
    Lorsque Blabla when...
    Alors Blabla then...

  Scénario: My scenario 2 french
    Soit Blabla given...
    # Noncompliant [[sc=5;ec=10]] {{Replace this redundant Given prefix with And or But.}}
    Soit Blabla given...
    Lorsque Blabla when...
    Alors Blabla then...
