Feature: My feature...

  Scenario Outline: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...
    # Noncompliant [[sc=5;ec=13]] {{Add a data table to this Examples section.}}
    Examples:

  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
    Examples:
      # Noncompliant [[sc=7;ec=15]] {{Add data rows to this data table.}}
      | test |

  Scenario Outline: Scenario 3
    Given blabla...
    When blabla...
    Then blabla...
    Examples:
      # Noncompliant [[sc=7;ec=15]] {{Add data rows to this data table or convert this Scenario Outline to a standard Scenario.}}
      | test |
      | 1    |
