Feature: My feature Missing Scenario name
  Blabla...

  Scenario: Scenario 1 Missing Scenario name
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: Scenario 2 Missing Scenario name
    Given blabla given...
    When blabla when...
    Then blabla then... <number>
    Examples:
      | number |
      | 1      |
      | 2      |

  # Noncompliant [[sc=3;ec=11]] {{Add a name to this scenario.}}
  Scenario:
    Given blabla given...
    When blabla when...
    Then blabla then...

  # Noncompliant [[sc=3;ec=19]] {{Add a name to this scenario.}}
  Scenario Outline:
    Given blabla given...
    When blabla when...
    Then blabla then... <number>
    Examples:
      | number |
      | 1      |
      | 2      |
