Feature: My feature Star step prefix
  Blabla...

  Scenario: My scenario 1 Star step prefix
    # Noncompliant [[sc=5;ec=6]] {{Replace this star prefix with one of the Given/When/Then prefixes.}}
    * blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 Star step prefix
    Given blabla...
    When blabla...
    Then blabla...
