Feature: My feature Star step prefix
  Blabla...

  Scenario: My scenario 1 - Star step prefix
    # Noncompliant [[sc=5;ec=7]] {{Replace this star prefix with one of the Given/When/Then prefixes.}}
    * Blabla...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 - Star step prefix
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
