Feature: My feature...

  Scenario: My scenario 1
    # Noncompliant [[sc=5;ec=6]] {{Replace this star prefix with Given/When/Then.}}
    * blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
