Feature: My feature Todo tag
  Blabla...

  # Noncompliant
  # TODO: blabla

  # Noncompliant
  #TODO: blabla

  # Noncompliant
  #[[TODO]] blabla

  # todoforthefirsttime

  Scenario: Scenario 1 Todo tag
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 Todo tag
    Given blabla given...
    When blabla when...
    Then blabla then...
