Feature: My feature Not only given
  Blabla...

  Background:
    Given Blabla g1...
    And Blabla g2...
    When Blabla when...
    And Blabla w1...
    Given Blabla g3...
    # Noncompliant [[sc=5;ec=22]] {{Move this Then step out of Background.}}
    Then Blabla g4...

  Scenario: Scenario 1 Not only given
    Given Blabla given1...
    When Blabla when1...
    Then Blabla then1...
