Feature: My feature Only given
  Blabla...

  Background:
    Given blabla g0...
    And blabla g1...
    But blabla g2...
    Given blabla g3...

  Scenario: Scenario 1 Only given
    Given blabla given...
    When blabla when...
    Then blabla then...
