@tag
@tag1
Feature: My feature indentation default ok
  blabla...
  blabla...

  Background: blabla background indentation default ok
    blabla...
    blabla...
    Given blabla givenT...

  @abc @def
  Scenario: Scenario 1 indentation default ok
    blabla...
    blabla...
    Given blabla given...
    When blabla when...
    Then blabla then...

  @ghi
  Scenario Outline: Scenario 2 indentation default ok
    blabla...
    blabla...
    Given blabla given...
    When blabla when...<data>
      | data |
      | 2    |
    Then blabla then...
      """string
      blabla...
        blabla...
      """

    @jkl
    @lmn @opq
    Examples: blabla examples indentation default ok
      blabla...
      blabla...
      | data |
      | 1    |
      | 2    |
