# Noncompliant [[sc=11;ec=44;secondary=+0]] {{Leave one single whitespace between the name and the column.}}
Feature:  My feature indentation default WS
  Blabla...
  Blabla...

  # Noncompliant [[sc=16;ec=56;secondary=+0]] {{Leave one single whitespace between the name and the column.}}
  Background:  Blabla background indentation default WS
    Blabla...
    Blabla...
    Given Blabla given blabla...

  # Noncompliant [[sc=15;ec=48;secondary=+0]] {{Leave one single whitespace between the name and the column.}}
  Scenario:   Scenario 1 indentation default WS
    Blabla...
    Blabla...
    Given Blabla given...
    When Blabla when...
    # Noncompliant [[sc=11;ec=25;secondary=+0]] {{Leave one single whitespace between the sentence and the prefix.}}
    Then  Blabla then...

  # Noncompliant [[sc=22;ec=55;secondary=+0]] {{Leave one single whitespace between the name and the column.}}
  Scenario Outline:  Scenario 2 indentation default WS
    Blabla...
    Blabla...
    Given Blabla given...
    When Blabla when...<data>
      | data |
      | 2    |
    Then Blabla then...
      """string
      Blabla...
        Blabla...
      """

    # Noncompliant [[sc=16;ec=54;secondary=+0]] {{Leave one single whitespace between the name and the column.}}
    Examples:  Blabla examples indentation default WS
      Blabla...
      Blabla...
      | data |
      | 1    |
      | 2    |
