Feature: My feature End line characters
  Blabla...

  Scenario: Scenario 1 End line characters
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 End line characters
    Given blabla given...
    When blabla when...
    Then blabla then...
