Feature: My feature Fixme tag
  Blabla...

  # Noncompliant {{Take the required action to fix the issue indicated by this comment.}}
  # FIXME: blabla

  # Noncompliant {{Take the required action to fix the issue indicated by this comment.}}
  #FIXME: blabla

  # Noncompliant {{Take the required action to fix the issue indicated by this comment.}}
  #[[FIXME]] blabla

  # fixmeforthefirsttime

  Scenario: Scenario 1 Fixme tag
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 Fixme tag
    Given blabla given...
    When blabla when...
    Then blabla then...
