Feature: my feature

  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
    Examples:
      | number |
      | 1      |
      | 2      |

  # Noncompliant [[sc=3;ec=11]] {{Add a name to this scenario.}}
  Scenario:
    Given blabla...
    When blabla...
    Then blabla...

  # Noncompliant [[sc=3;ec=19]] {{Add a name to this scenario.}}
  Scenario Outline:
    Given blabla...
    When blabla...
    Then blabla...
    Examples:
      | number |
      | 1      |
      | 2      |