Feature: My feature One single when step per scenario
  Blabla...

  Scenario Outline: Scenario 1 - One single when step per scenario
    Given Blabla given...
    When Blabla when... <number>
    # Noncompliant [[sc=5;ec=24;secondary=+1]] {{Merge all the Then steps or split the scenario up in multiple scenarios.}}
    Then Blabla then...
    And Blabla when and blabla then
    Examples:
      | number |
      | 1      |
      | 2      |

  Scenario: Scenario 2 - One single when step per scenario
    Given Blabla given...
    When Blabla when...
    # Noncompliant [[sc=5;ec=40;secondary=+1]] {{Merge all the Then steps or split the scenario up in multiple scenarios.}}
    Then Blabla when and blabla then...
    Then Blabla then...
