# Noncompliant [[sl=+2;sc=1;ec=8;secondary=5,11,24]] {{Add tag "mytag2" to this feature and remove it from all scenarios.}}
@mytag
Feature: My feature...

  @mytag @mytag2 @abc
  Scenario: My scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  @mytag @mytag2
  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
    Examples:

  @abc
  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...

    @mytag @mytag2
    Examples:
