# Noncompliant [[sl=3]] {{Remove the useless trailing whitespaces at the end of this line.}}
# Noncompliant [[sl=6]] {{Remove the useless trailing whitespaces at the end of this line.}}
Feature: My feature...  

  Scenario: Scenario 1
    Given blabla...  
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...

