# Noncompliant [[sl=3]] {{Remove the useless trailing whitespaces at the end of this line.}}
# Noncompliant [[sl=7]] {{Remove the useless trailing whitespaces at the end of this line.}}
Feature: My feature Trailing white space 
  Blabla...

  Scenario: Scenario 1 Trailing white space
    Given Blabla given...  
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 Trailing white space
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

