Feature: My feature Use And But
  Blabla...

  Scenario: Scenario 1 Use And But
    Given blabla given1...
    # Noncompliant [[sc=5;ec=10]] {{Replace this redundant Given prefix with And or But.}}
    Given blabla given2...
    When blabla when...
    Then blabla then...

  Scenario Outline: Scenario 2 Use And But
    Given blabla given1...
    # Noncompliant [[sc=5;ec=10]] {{Replace this redundant Given prefix with And or But.}}
    Given blabla given2...
    When blabla when...
    Then blabla then...<number>
    Examples:
      | number |
      | 1      |
      | 2      |

  Scenario: Scenario 3 Use And But
    Given blabla given...
    And blabla...
    When blabla when...
    # Noncompliant [[sc=5;ec=9]] {{Replace this redundant When prefix with And or But.}}
    When blabla when1...
    Then blabla then...

  Scenario: Scenario 4 Use And But
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 5 Use And But
    And blabla...
    Given blabla given...
    When blabla when...
    Then blabla then...
