Feature: My feature...

  Scenario: Scenario 1
    Given blabla...
    # Noncompliant [[sc=5;ec=10]] {{Replace this redundant prefix with And or But.}}
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: Scenario 1
    Given blabla...
    # Noncompliant [[sc=5;ec=10]] {{Replace this redundant prefix with And or But.}}
    Given blabla...
    When blabla...
    Then blabla...
    Examples:

  Scenario: Scenario 1
    Given blabla...
    And blabla...
    When blabla...
    # Noncompliant [[sc=5;ec=9]] {{Replace this redundant prefix with And or But.}}
    When blabla...

  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 1
    And blabla...
    Given blabla...
    When blabla...
    Then blabla...