@mytag
Feature: My feature...

  # Noncompliant [[sc=13;ec=19;secondary=1]] {{Remove this useless tag that is already set at feature level.}}
  @othertag @mytag
  Scenario: My scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  # Noncompliant [[sc=3;ec=9;secondary=1]] {{Remove this useless tag that is already set at feature level.}}
  @mytag @abc
  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...

    # Noncompliant [[sc=5;ec=11;secondary=1]] {{Remove this useless tag that is already set at feature level.}}
    @mytag @def
    Examples:

  @othertag
  Scenario: My scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  @abc
  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...

    @def
    Examples:
