@bar
Feature: My feature forbidden tag...
  Blabla...

  @foo
  Scenario: Scenario 1 forbidden tag
    Given blabla...
    When blabla...
    Then blabla...

  @mytag
  Scenario: Scenario 2 forbidden tag
    Given blabla...
    When blabla...
    Then blabla...
