# Noncompliant [[sl=0]] {{Remove the Byte Order Mark (BOM).}}
Feature: My feature utf8 with byte order mark...
  Blabla...

  Scenario: Scenario 1 utf8 with byte order mark
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 utf8 with byte order mark
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
