# Noncompliant [[sl=0]] {{Remove the Byte Order Mark (BOM).}}
Feature: My feature utf8 with bom...

  Scenario: Scenario 1 utf8 with bom
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 utf8 with bom
    Given blabla...
    When blabla...
    Then blabla...
