# Noncompliant [[sl=0]] {{Remove the Byte Order Mark (BOM).}}
Feature: My feature utf8 with bom...
  Blabla...

  Scenario: Scenario 1 utf8 with bom
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 utf8 with bom
    Given blabla given...
    When blabla when...
    Then blabla then...
