Feature: My feature utf8...
  Blabla...

  Scenario: Scenario 1 utf8
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 utf8
    Given blabla given...
    When blabla when...
    Then blabla then...
