@bar
Feature: My feature forbidden tag...
  Blabla...

  @foo
  Scenario: Scenario 1 forbidden tag
    Given blabla given...
    When blabla when...
    Then blabla then...

  @mytag
  Scenario: Scenario 2 forbidden tag
    Given blabla given...
    When blabla when...
    Then blabla then...
