Feature: My feature New line end of file

  Scenario: Scenario #1 New line end of file
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario #2 New line end of file
    Given blabla...
    When blabla...
    Then blabla...
