Feature: My feature No new line end of file
  Blabla...

  Scenario: Scenario #1 No new line end of file
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 No new line end of file
    Given blabla...
    When blabla...
    Then blabla...