Feature: My feature...

  Scenario: scenario #1
    Given blabla...
    When blabla...
    Then blabla...
    And blabla...
    And blabla...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (7, greater than 5 allowed)}}
  Scenario: scenario #2
    Given blabla...
    When blabla...
    Then blabla...
    And blabla...
    And blabla...
    And blabla...
    And blabla...
