Feature: My feature max number steps no background...
  Blabla...

  Scenario: scenario #1 max number steps no background
    Given blabla given...
    When blabla when...
    Then blabla then...
    And blabla t1...
    And blabla t2...
    And blabla t3...
    And blabla t4...
    And blabla t5...
    And blabla t6...
    And blabla t7...
    And blabla t8...
    And blabla t9...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (13, greater than 12 allowed).}}
  Scenario: scenario #2 max number steps no background
    Given blabla given...
    When blabla when...
    Then blabla then...
    And blabla t1...
    And blabla t2...
    And blabla t3...
    And blabla t4...
    And blabla t5...
    And blabla t6...
    And blabla t7...
    And blabla t8...
    And blabla t9...
    And blabla t10...
