Feature: My feature max number steps background...
  Blabla...

  Background:
    Given blabla given1...
    And blabla b1...
    And blabla b2...
    And blabla b3...
    And blabla b4...

  Scenario: scenario #1 max number steps background
    Given blabla given...
    When blabla when...
    Then blabla then...
    And blabla t1...
    And blabla t2...
    And blabla t3...
    And blabla t4...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (13, greater than 12 allowed).}}
  Scenario: scenario #2 max number steps background
    Given blabla given...
    When blabla when...
    Then blabla then...
    And blabla t1...
    And blabla t2...
    And blabla t3...
    And blabla t4...
    And blabla t5...
