Feature: My feature max number steps custom threshold...
  Blabla...

  Scenario: Scenario #1 max number steps custom threshold
    Given Blabla given1...
    When Blabla when...
    Then Blabla then...
    And Blabla t1...
    And Blabla t2...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (7, greater than 5 allowed).}}
  Scenario: Scenario #2 max number steps custom threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
    And Blabla t1...
    And Blabla t2...
    And Blabla t3...
    And Blabla t4...
