Feature: My feature max number steps custom threshold...
  Blabla...

  Scenario: scenario #1 max number steps custom threshold
    Given blabla...
    When blabla...
    Then blabla...
    And blabla...
    And blabla...

  # Noncompliant [[sc=3;ec=11]] {{Reduce the number of steps (7, greater than 5 allowed).}}
  Scenario: scenario #2 max number steps custom threshold
    Given blabla...
    When blabla...
    Then blabla...
    And blabla...
    And blabla...
    And blabla...
    And blabla...
