Feature: My feature Steps
  Blabla...

  Background:
    Given blabla...

  Scenario: Scenario 1 Steps
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: Scenario 2 Steps
    Given blabla...
    When blabla...
    Then blabla...<number>
    Examples:
      | number |
      | 1      |
      | 2      |
