Feature: My feature file name...
  Blabla...

  Scenario: Scenario 1 - file name
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 - file name
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
