Feature: My feature file name KO...
  Blabla...

  Scenario: Scenario 1 - file name KO
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 - file name KO
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
