@mytag
Feature: My feature...

  # blabla...
  # blabla...
  @nrt
  Scenario: Scenario #1
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #2
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario Outline: Scenario #2
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Examples:
  |d1|
