# Noncompliant [[sc=1;ec=7]] {{Rename this tag to match the regular expression: ^[a-z][-a-z0-9]*$}}
@myTag @my-tag
Feature: My feature...

  # Noncompliant [[sc=3;ec=10]] {{Rename this tag to match the regular expression: ^[a-z][-a-z0-9]*$}}
  @myTag0
  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
