@mytag @my-tag
Feature: My feature Tag name OK
  Blabla...

  @my-tag1
  Scenario: Scenario 1 Tag name OK
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 Tag name OK
    Given blabla given...
    When blabla when...
    Then blabla then...
