@my-tag
Feature: My feature Tag name custom OK
  Blabla...

  @tag
  Scenario: Scenario 1 Tag name custom OK
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 Tag name custom OK
    Given blabla...
    When blabla...
    Then blabla...
