@mytag @my-tag
Feature: My feature Tag name OK

  @my-tag1
  Scenario: Scenario 1 Tag name OK
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 Tag name OK
    Given blabla...
    When blabla...
    Then blabla...
