Feature: My feature No tab character...
  Blabla...

  Scenario: Scenario 1  No tab character
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2  No tab character
    Given blabla given...
    When blabla when...
    Then blabla then...
