Feature: My feature No tab character...

  Scenario: Scenario 1  No tab character
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2  No tab character
    Given blabla...
    When blabla...
    Then blabla...
