Feature: My feature Tab character...

  Scenario: Scenario 1 Tab character
	Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2 Tab character
    Given blabla...
    When blabla...
    Then blabla...
