# Noncompliant [[sc=1;ec=8;secondary=6,7,12,13]] {{Add a Background to group common Given steps.}}
Feature: My feature background to create...
  Blabla...

  Scenario: Scenario 1 background to create
    Given abc
    And def
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 background to create
    Given abc
    And def
    And hij
    When blabla when...
    Then blabla then...
