# Noncompliant [[sc=1;ec=8;secondary=5,6,11,12]] {{Add a Background to group common Given steps.}}
Feature: My feature background to create...

  Scenario: Scenario 1 background to create
    Given abc
    And def
    When blabla...
    Then blabla...

  Scenario: Scenario 2 background to create
    Given abc
    And def
    And hij
    When blabla...
    Then blabla...
