Feature: My feature no background to create...

  Scenario: Scenario 1 no background to create
    Given abc
    And def
    When blabla...
    Then blabla...

  Scenario: Scenario 2 no background to create
    Given def
    When blabla...
    Then blabla...
