Feature: My feature Steps
  Blabla...

  Background:
    Given blabla given1...

  Scenario: Scenario 1 Steps
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: Scenario 2 Steps
    Given blabla given...
    When blabla when...
    Then blabla then...<number>
    Examples:
      | number |
      | 1      |
      | 2      |
