Feature: My feature

  Background:
    Given blabla...

  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
    Examples:
      | number |
      | 1      |
      | 2      |
