Feature: My feature Steps
  Blabla...

  Background:
    Given Blabla given1...

  Scenario: Scenario 1 Steps
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario Outline: Scenario 2 Steps
    Given Blabla given...
    When Blabla when...
    Then Blabla then...<number>
    Examples:
      | number |
      | 1      |
      | 2      |
