Feature: My feature...

  #blabla...
  #blabla...
  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...