Feature: My feature...

  #blabla...
  #blabla...
  Scenario: Scenario 1
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2
    Given Blabla given...
    When Blabla when...
    Then Blabla then...