# language: fr
Fonctionnalité: My feature...

  #blabla...
  #blabla...
  Scénario: : Scenario 1
    Soit Blabla given...
    Lorsque Blabla when...
    Alors Blabla then...

  Scénario: : Scenario 2
    Soit Blabla given...
    Lorsque Blabla when...
    Alors Blabla then...