Feature: My feature...

  #blabla...
  #blabla...
  Scenario: Scenario 1
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2
    Given blabla given...
    When blabla when...
    Then blabla then...