@mytag @nrt
Feature: My feature...

  # blabla...
  # blabla...
  Scenario: Scenario #1
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  @nrt
  Scenario Outline: Scenario #3
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Examples:
  |d1|
