Feature: My feature No tab character...
  Blabla...

  Scenario: Scenario 1 - No tab character
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 - No tab character
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
