Feature: My feature Tab character...
  Blabla...

  Scenario: Scenario 1 Tab character
	Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 Tab character
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
