Feature: My feature Tab character...
  Blabla...

  Scenario: Scenario 1 Tab character
	Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 Tab character
    Given blabla given...
    When blabla when...
    Then blabla then...
