# Noncompliant [[sc=1;ec=8;secondary=6,7,12,13]] {{Add a Background to group common Given steps.}}
Feature: My feature background to create...
  Blabla...

  Scenario: Scenario 1 background to create
    Given Car
    And Bike
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 background to create
    Given Car
    And Bike
    And Book
    When Blabla when...
    Then Blabla then...
