Feature: My feature no background to create...
  Blabla...

  Scenario: Scenario 1 no background to create
    Given Car
    And Bike
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario 2 no background to create
    Given Car
    When Blabla when...
    Then Blabla then...
