Feature: My feature no background to create...
  Blabla...

  Scenario: Scenario 1 no background to create
    Given abc
    And def
    When blabla when...
    Then blabla then...

  Scenario: Scenario 2 no background to create
    Given def
    When blabla when...
    Then blabla then...
