# Noncompliant [[sc=1;ec=7]] {{Remove this tag that is not in the whitelist.}}
@mytag
Feature: My feature allowed tags default...
  Blabla...

  # Noncompliant [[sc=3;ec=23]] {{Remove this tag that is not in the whitelist.}}
  @non-regression-test
  Scenario: Scenario 1 allowed tags default
    Given blabla given...
    When blabla when...
    Then blabla then...

  @nrt @smoke
  Scenario: Scenario 2 allowed tags default
    Given blabla given...
    When blabla when...
    Then blabla then...
