# Noncompliant [[sc=1;ec=5]] {{Remove this tag that is not in the whitelist.}}
@nrt
Feature: My feature...

  # Noncompliant [[sc=3;ec=23]] {{Remove this tag that is not in the whitelist.}}
  @non-regression-test
  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  @mytag @yourtag
  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
