# Noncompliant [[sc=1;ec=8]] {{Remove this tag that is not in the whitelist.}}
@us:abc
Feature: My feature allowed tags custom...
  Blabla...

  # Noncompliant [[sc=3;ec=11]] {{Remove this tag that is not in the whitelist.}}
  @uid:A_B
  Scenario: Scenario 1 allowed tags custom
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  @us:123 @uid:UniqueID
  Scenario: Scenario 2 allowed tags custom
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
