# Noncompliant [[sc=1;ec=8]] {{Remove this tag that does not match the regular expression: "us:\d+|uid:[a-zA-Z''-'\s]{1,40}"}}
@us:abc
Feature: My feature allowed tags composite...
  Blabla...

  # Noncompliant [[sc=3;ec=11]] {{Remove this tag that does not match the regular expression: "us:\d+|uid:[a-zA-Z''-'\s]{1,40}"}}
  @uid:A_B
  Scenario: Scenario 1 allowed tags composite
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  @us:123 @uid:UniqueID
  Scenario: Scenario 2 allowed tags composite
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
