# Noncompliant [[sc=1;ec=7]] {{Remove this tag that is not in the whitelist.}}
@mytag
Feature: My feature...

  # Noncompliant [[sc=3;ec=23]] {{Remove this tag that is not in the whitelist.}}
  @non-regression-test
  Scenario: Scenario 1
    Given blabla...
    When blabla...
    Then blabla...

  @nrt @smoke
  Scenario: Scenario 2
    Given blabla...
    When blabla...
    Then blabla...
