Feature: My feature...

  Scenario: Scenario #1
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: Scenario WTF #2
    Given blabla given...
    When blabla when...
    Then blabla then...
