Feature: My feature all step types without background
  Blabla...

  Scenario: Scenario 1 all step types without background
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: Scenario 2 all step types without background
    Given blabla given...
    When blabla when...
    Then blabla then...<number>
    Examples:
      | number |
      | 1      |
      | 2      |

  # Noncompliant [[sc=3;ec=11]] {{Add at least one Given step.}}
  Scenario: Scenario 3 all step types without background
    When blabla when...
    Then blabla then...

  # Noncompliant [[sc=3;ec=11]] {{Add at least one When step.}}
  Scenario: Scenario 4 all step types without background
    Given blabla given...
    Then blabla then...

  # Noncompliant [[sc=3;ec=11]] {{Add at least one Then step.}}
  Scenario: Scenario 5 all step types without background
    Given blabla given...
    When blabla when...

  # Noncompliant [[sc=3;ec=19]] {{Add at least one Then step.}}
  Scenario Outline: Scenario 5 all step types without background
    Given blabla given...
    When blabla when...<number>
    Examples:
      | number |
      | 1      |
      | 2      |
