# Noncompliant [[sc=1;ec=8]] {{The number of scenarios (13) is greater that the maximum allowed (12). Split the scenarios into different features.}}
Feature: My feature...

  Background:
    Given blabla...

  Scenario: scenario #1
    Given blabla...

  Scenario Outline: scenario #2
    Given blabla...
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3
    Given blabla...

  Scenario: scenario #4
    Given blabla...

  Scenario: scenario #5
    Given blabla...

  Scenario: scenario #6
    Given blabla...

  Scenario: scenario #7
    Given blabla...

  Scenario: scenario #8
    Given blabla...

  Scenario: scenario #9
    Given blabla...

  Scenario: scenario #10
    Given blabla...

  Scenario: scenario #11
    Given blabla...

  Scenario: scenario #12
    Given blabla...

  Scenario: scenario #13
    Given blabla...
