# Noncompliant [[sc=1;ec=8]] {{The number of scenarios (5) is greater that the maximum allowed (4). Split the scenarios into different features.}}
Feature: My feature max number scenarios greater than custom threshold...
  Blabla...

  Background:
    Given blabla given1...

  Scenario: scenario #1 max number scenarios greater than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: scenario #2 max number scenarios greater than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...<data>
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3 max number scenarios greater than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #4 max number scenarios greater than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #5 max number scenarios greater than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...
