Feature: My feature max number scenarios lower than default threshold...
  Blabla...

  Background:
    Given Blabla given1...

  Scenario: Scenario #1 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario Outline: Scenario #2 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...<data>
    Then Blabla then...
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: Scenario #3 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #4 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #5 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #6 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #7 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #8 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #9 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #10 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #11 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...

  Scenario: Scenario #12 max number scenarios lower than default threshold
    Given Blabla given...
    When Blabla when...
    Then Blabla then...
