Feature: My feature max number scenarios lower than default threshold...

  Background:
    Given blabla...

  Scenario: scenario #1 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: scenario #2 max number scenarios lower than default threshold
    Given blabla...
    When blabla...<data>
    Then blabla...
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #4 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #5 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #6 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #7 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #8 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #9 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #10 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #11 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #12 max number scenarios lower than default threshold
    Given blabla...
    When blabla...
    Then blabla...
