Feature: My feature max number scenarios lower than custom threshold...

  Background:
    Given blabla...

  Scenario: scenario #1 max number scenarios lower than custom threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario Outline: scenario #2 max number scenarios lower than custom threshold
    Given blabla...
    When blabla...
    Then blabla...<data>
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3 max number scenarios lower than custom threshold
    Given blabla...
    When blabla...
    Then blabla...

  Scenario: scenario #4 max number scenarios lower than custom threshold
    Given blabla...
    When blabla...
    Then blabla...
