Feature: My feature max number scenarios lower than custom threshold...
  Blabla...

  Background:
    Given blabla given1...

  Scenario: scenario #1 max number scenarios lower than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario Outline: scenario #2 max number scenarios lower than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...<data>
    Examples:
      | data |
      | 1    |
      | 2    |

  Scenario: scenario #3 max number scenarios lower than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...

  Scenario: scenario #4 max number scenarios lower than custom threshold
    Given blabla given...
    When blabla when...
    Then blabla then...
