# Noncompliant [[sc=1;ec=8;secondary=5,6,11,12]] {{Add a Background to group common Given steps.}}
Feature: My feature...

  Scenario: Scenario 1
    Given abc
    And def
    When blabla...
    Then blabla...

  Scenario: Scenario 2
    Given abc
    And def
    And hij
    When blabla...
    Then blabla...
